#!/bin/bash
if [ "$#" -eq  "0" ]; then
    echo "$0 [hostname (example.com)] {proxy [proxy port]}"
else
    if [ "$2" = "proxy" ]; then
	PROXY="proxy_pass http://127.0.0.1:$3;"
    else
	PROXY="autoindex on;"
    fi
    HOSTNAME=$1
    cat <<EOF > "/etc/nginx/sites-enabled/$HOSTNAME.conf"
server {
       listen 80;
       server_name www.$HOSTNAME;
       return 301 http://www.$HOSTNAME\$request_uri;
}

server {
       listen 80;
       server_name $HOSTNAME;
       access_log /var/log/nginx/$HOSTNAME.log;
       error_log /var/log/nginx/$HOSTNAME.error.log;
       root /var/www/$HOSTNAME/current;

       gzip on;
       gzip_disable "msie6";

       gzip_vary on;
       gzip_proxied any;
       gzip_comp_level 6;
       gzip_buffers 16 8k;
       gzip_http_version 1.1;
       gzip_types text/plain text/css application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript application/javascript;


       location / {
            $PROXY
       }
}
EOF
fi
rm /etc/nginx/sites-enabled/*~
/etc/init.d/nginx reload
